### ISSUE TITLE
`sqd up` command miss configuration

### ISSUE THREAD

**Issue by hossam4444** [subsquid-labs/evm-logs-example#47]
### the behavior :
- when using `sqd up` command you get docker-compose complaining about wrong command 

### hint :
- which can be located in the commands.json at the `up` command
- like so 
![image](https://github.com/subsquid-labs/evm-logs-example/assets/57760803/636778f3-787e-4450-9602-2a70ffa1a832)

**Comment by abernatskiy** [comment]
Use newer docker or correct the command manually
